### ISSUE TITLE
Error During Compilation with 'make'

### ISSUE THREAD

**Issue by vijjay29** [uricamic/flandmark#27]
As mentioned in INSTALL file in Flanmark-master, I Followed instructions.
Finally during compilation i got the following errors.

[ 71%] Building CXX object examples/CMakeFiles/flandmark_1.dir/example1.cpp.o
/home/vijay/Flandmark/flandmark-master/examples/example1.cpp:11:16: fatal error: cv.h: No such file or directory
 #include <cv.h>
                ^
compilation terminated.
examples/CMakeFiles/flandmark_1.dir/build.make:54: recipe for target 'examples/CMakeFiles/flandmark_1.dir/example1.cpp.o' failed
make[2]: **\* [examples/CMakeFiles/flandmark_1.dir/example1.cpp.o] Error 1
CMakeFiles/Makefile2:166: recipe for target 'examples/CMakeFiles/flandmark_1.dir/all' failed
make[1]: **\* [examples/CMakeFiles/flandmark_1.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by uricamic** [comment]
Hi, 

it seems you don't have the path to OpenCV setup correctly in CMake. What version of OpenCV are you using? Have you compiled it from the source code or is it some package for your system distribution?

**Comment by vijjay29** [comment]
Hi, 
I've OpenCV 3.0.0
I've compiled it from the package.
also this is my path to OpenCV
/usr/local/share/OpenCV

**Comment by uricamic** [comment]
Hi, 

that would be the problem. I guess, you will have to modify the includes and also some constants used from OpenCV, since version 3.0 is not backward compatible with 2.x versions. 

Another option is to compile older version of OpenCV (2.x) to use with flandmark. You don't have to install it, since CMake gives you nice option of selecting version you need.

**Comment by vijjay29** [comment]
So shall i remove OpenCV 3.0.0 completely and try with lower version ??
is it recommended ??
or 
I cant get your second option sir, Could you tell me briefly.

**Comment by uricamic** [comment]
Depends on you, if you are using OpenCV 3.0 for your needs everywhere and you know what to change in flandmark code that is one option. 

Second option is to compile another version of OpenCV (2.x), which you don't have to install in your system path (and keep using version 3.0 as default). And in CMake process of flandmark just provide this 2.x version. This solution does not require you to change flandmark code in any way, but you will have to download and compile another version of OpenCV library.

**Comment by vijjay29** [comment]
Hi sir,
Till now i've tried to compile Opencv 2.4.9

I am getting error during make.
Also i refered several fourms, tried solutions.
But i coud'n fix it.
Seeking your help now

Reference:

[ 10%] Building CXX object
modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o
.
.
.
.
.
.

modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:100: recipe for
target 'modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o'
failed
make[2]: ***
[modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o] Error 1
CMakeFiles/Makefile2:1719: recipe for target
'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
make[1]: **\* [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2

warm regards,

**Comment by vijjay29** [comment]
Issue Solved, Actually Error was using OpenCV 3.0 which is not backward compatible with lower version.
Used OpenCV 2.4.9 with Ubuntu 14.04LTS
Thanks @uricamic.

**Comment by ndiayefrancisco2000** [comment]
@vijjay29 I don't understand how you fixed your problem. I'm installing OpenCv 2.4.9 now since 2.4.10 was giving me an error during make, but i'm getting another error during make of 2.4.9.

modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:100: recipe for target                                                                              'modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o' failed
make[2]: **\* [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o                                                                             ] Error 1
CMakeFiles/Makefile2:1563: recipe for target 'modules/highgui/CMakeFiles/opencv_                                                                             highgui.dir/all' failed
make[1]: **\* [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by uricamic** [comment]
Hi @ndiayefrancisco2000, 

I guess the problem is in ffmpeg, which is probably missing. You can try to compile with `WITH_FFMPEG=OFF` flag.
