### ISSUE TITLE
Installation queries

### ISSUE THREAD

**Issue by msharmavikram** [uricamic/flandmark#37]
I am a linux user with no access to Matlab. 
I would like to know what are the dependencies for this library and is it possible to install this without matlab? 

Further, appreciate a more detailed installation instructions.

**Comment by uricamic** [comment]
Hi @msharmavikram, 

thank you for your interest in flandmark library. Flandmark has dependency on OpenCV (version 2.x) only. The installation instructions are summarized in [this document](https://github.com/uricamic/flandmark/blob/master/INSTALL), basically it is a standard CMake compilation procedure. You can turn off the `BUILD_MATLAB_BINDINGS` if you are not interested in the Matlab interface. 

Since flandmark is considered to be obsolete and is not in active development anymore, I would recommend you to try the completely rewritten version of the library called [CLandmark](https://github.com/uricamic/clandmark), it does not have any external dependencies (there are some external libraries used, but they come up with the library and do not require linking or separate compilation). There is also an interface to Python (not completely finished, but usable for applications). Also the installation process is described there and is quite simple on Linux systems. 

I am closing this issue, however, feel free to reopen if you have more questions.
